'type: components':
    - any-glob-to-any-file:src/components/**/*
  
'type: guides':
    - any-glob-to-any-file:src/content/docs/guides/**/*
  
'type: functions':
    - src/content/docs/functions/**/*
  
'type: extensions':
    - src/content/docs/extensions/**/*
  
'type: config':
    - src/content/config.ts
    - astro.config.mjs
