name: Label Pull Requests

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, reopened, ready_for_review, closed]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Label PRs
        uses: actions/labeler@v4
